# Generated by Django 2.1 on 2019-08-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_played', models.CharField(max_length=100, verbose_name='Sport Name')),
                ('achievement', models.CharField(max_length=100, verbose_name='Students Achievement')),
                ('year_participated', models.IntegerField(verbose_name='Year Participated')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_admno', models.IntegerField(primary_key=True, serialize=False, verbose_name='Admin Number')),
                ('student_gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('student_classcode', models.CharField(max_length=10, verbose_name='Class Code')),
                ('student_grade', models.IntegerField(null=True, verbose_name='Grade')),
                ('student_class_designation', models.CharField(max_length=1, null=True, verbose_name='Class Designation')),
                ('student_fullname', models.CharField(max_length=200, verbose_name='Full Name')),
                ('student_firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('student_middlename', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('student_lastname', models.CharField(max_length=50, verbose_name='Last Name')),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
