# Generated by Django 2.2.1 on 2019-08-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_admno', models.IntegerField(primary_key=True, serialize=False)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_classcode', models.CharField(max_length=10)),
                ('student_fullname', models.CharField(max_length=200)),
                ('student_firstname', models.CharField(max_length=50)),
                ('student_middlename', models.CharField(blank=True, max_length=50)),
                ('student_lastname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_played', models.CharField(max_length=100)),
                ('achievement', models.CharField(max_length=100)),
                ('year_participated', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
