# Generated by Django 2.1 on 2019-08-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_middlename',
        ),
    ]
